services:
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "0.0.0.0:5432:5432"

  web:
    build: .
    command: sh -c "while ! nc -z db 5432; do sleep 1; done && uvicorn main:app --host 0.0.0.0 --port 8000"
    volumes:
    - ./app:/app
    ports:
      - "8000:8000"
    environment:
      DB_URL: postgresql+psycopg2://postgres:postgres@db:5432/postgres
    depends_on:
      - db

volumes:
  postgres_data:
